const countries = [
  { id: 1, code: "AF", title: "Afghanistan" },
  { id: 2, code: "AL", title: "Albania" },
  { id: 3, code: "DZ", title: "Algeria" },
  { id: 4, code: "AS", title: "American Samoa" },
  { id: 5, code: "AD", title: "Andorra" },
  { id: 6, code: "AO", title: "Angola" },
  { id: 7, code: "AI", title: "Anguilla" },
  { id: 8, code: "AG", title: "Antigua and Barbuda" },
  { id: 9, code: "AR", title: "Argentina" },
  { id: 10, code: "AM", title: "Armenia" },
  { id: 11, code: "AW", title: "Aruba" },
  { id: 12, code: "AU", title: "Australia" },
  { id: 13, code: "AT", title: "Austria" },
  { id: 14, code: "AZ", title: "Azerbaijan" },
  { id: 15, code: "BS", title: "Bahamas" },
  { id: 16, code: "BH", title: "Bahrain" },
  { id: 17, code: "BD", title: "Bangladesh" },
  { id: 18, code: "BB", title: "Barbados" },
  { id: 19, code: "BY", title: "Belarus" },
  { id: 20, code: "BE", title: "Belgium" },
  { id: 21, code: "BZ", title: "Belize" },
  { id: 22, code: "BJ", title: "Benin" },
  { id: 23, code: "BM", title: "Bermuda" },
  { id: 24, code: "BT", title: "Bhutan" },
  {
    id: 25,
    code: "BO",
    title: "Bolivia, Plurinational State of",
  },
  { id: 26, code: "BA", title: "Bosnia and Herzegovina" },
  { id: 27, code: "BW", title: "Botswana" },
  { id: 28, code: "BR", title: "Brazil" },
  {
    id: 29,
    code: "IO",
    title: "British Indian Ocean Territory",
  },
  { id: 30, code: "BG", title: "Bulgaria" },
  { id: 31, code: "BF", title: "Burkina Faso" },
  { id: 32, code: "BI", title: "Burundi" },
  { id: 33, code: "KH", title: "Cambodia" },
  { id: 34, code: "CM", title: "Cameroon" },
  { id: 35, code: "CA", title: "Canada" },
  { id: 36, code: "CV", title: "Cape Verde" },
  { id: 37, code: "KY", title: "Cayman Islands" },
  { id: 38, code: "CF", title: "Central African Republic" },
  { id: 39, code: "TD", title: "Chad" },
  { id: 40, code: "CL", title: "Chile" },
  { id: 41, code: "CN", title: "China" },
  { id: 42, code: "CO", title: "Colombia" },
  { id: 43, code: "KM", title: "Comoros" },
  { id: 44, code: "CG", title: "Congo" },
  {
    id: 45,
    code: "CD",
    title: "Democratic Republic of the Congo",
  },
  { id: 46, code: "CK", title: "Cook Islands" },
  { id: 47, code: "CR", title: "Costa Rica" },
  { id: 48, code: "CI", title: "C√¥te d'Ivoire" },
  { id: 49, code: "HR", title: "Croatia" },
  { id: 50, code: "CU", title: "Cuba" },
  { id: 51, code: "CW", title: "Cura√ßao" },
  { id: 52, code: "CY", title: "Cyprus" },
  { id: 53, code: "CZ", title: "Czech Republic" },
  { id: 54, code: "DK", title: "Denmark" },
  { id: 55, code: "DJ", title: "Djibouti" },
  { id: 56, code: "DM", title: "Dominica" },
  { id: 57, code: "DO", title: "Dominican Republic" },
  { id: 58, code: "EC", title: "Ecuador" },
  { id: 59, code: "EG", title: "Egypt" },
  { id: 60, code: "SV", title: "El Salvador" },
  { id: 61, code: "GQ", title: "Equatorial Guinea" },
  { id: 62, code: "ER", title: "Eritrea" },
  { id: 63, code: "EE", title: "Estonia" },
  { id: 64, code: "ET", title: "Ethiopia" },
  {
    id: 65,
    code: "FK",
    title: "Falkland Islands (Malvinas)",
  },
  { id: 66, code: "FO", title: "Faroe Islands" },
  { id: 67, code: "FJ", title: "Fiji" },
  { id: 68, code: "FI", title: "Finland" },
  { id: 69, code: "FR", title: "France" },
  { id: 70, code: "PF", title: "French Polynesia" },
  { id: 71, code: "GA", title: "Gabon" },
  { id: 72, code: "GM", title: "Gambia" },
  { id: 73, code: "GE", title: "Georgia" },
  { id: 74, code: "DE", title: "Germany" },
  { id: 75, code: "GH", title: "Ghana" },
  { id: 76, code: "GI", title: "Gibraltar" },
  { id: 77, code: "GR", title: "Greece" },
  { id: 78, code: "GL", title: "Greenland" },
  { id: 79, code: "GD", title: "Grenada" },
  { id: 80, code: "GU", title: "Guam" },
  { id: 81, code: "GT", title: "Guatemala" },
  { id: 82, code: "GG", title: "Guernsey" },
  { id: 83, code: "GN", title: "Guinea" },
  { id: 84, code: "GW", title: "Guinea-Bissau" },
  { id: 85, code: "HT", title: "Haiti" },
  { id: 86, code: "HN", title: "Honduras" },
  { id: 87, code: "HK", title: "Hong Kong" },
  { id: 88, code: "HU", title: "Hungary" },
  { id: 89, code: "IS", title: "Iceland" },
  { id: 90, code: "IN", title: "India" },
  { id: 91, code: "ID", title: "Indonesia" },
  {
    id: 92,
    code: "IR",
    title: "Iran, Islamic Republic of",
  },
  { id: 93, code: "IQ", title: "Iraq" },
  { id: 94, code: "IE", title: "Ireland" },
  { id: 95, code: "IM", title: "Isle of Man" },
  { id: 96, code: "IL", title: "Israel" },
  { id: 97, code: "IT", title: "Italy" },
  { id: 98, code: "JM", title: "Jamaica" },
  { id: 99, code: "JP", title: "Japan" },
  { id: 100, code: "JE", title: "Jersey" },
  { id: 101, code: "JO", title: "Jordan" },
  { id: 102, code: "KZ", title: "Kazakhstan" },
  { id: 103, code: "KE", title: "Kenya" },
  { id: 104, code: "KI", title: "Kiribati" },
  { id: 105, code: "KP", title: "North Korea" },
  { id: 106, code: "KR", title: "South Korea" },
  { id: 107, code: "KW", title: "Kuwait" },
  { id: 108, code: "KG", title: "Kyrgyzstan" },
  {
    id: 109,
    code: "LA",
    title: "Lao People's Democratic Republic",
  },
  { id: 110, code: "LV", title: "Latvia" },
  { id: 111, code: "LB", title: "Lebanon" },
  { id: 112, code: "LS", title: "Lesotho" },
  { id: 113, code: "LR", title: "Liberia" },
  { id: 114, code: "LY", title: "Libya" },
  { id: 115, code: "LI", title: "Liechtenstein" },
  { id: 116, code: "LT", title: "Lithuania" },
  { id: 117, code: "LU", title: "Luxembourg" },
  { id: 118, code: "MO", title: "Macao" },
  { id: 119, code: "MK", title: "Republic of Macedonia" },
  { id: 120, code: "MG", title: "Madagascar" },
  { id: 121, code: "MW", title: "Malawi" },
  { id: 122, code: "MY", title: "Malaysia" },
  { id: 123, code: "MV", title: "Maldives" },
  { id: 124, code: "ML", title: "Mali" },
  { id: 125, code: "MT", title: "Malta" },
  { id: 126, code: "MH", title: "Marshall Islands" },
  { id: 127, code: "MQ", title: "Martinique" },
  { id: 128, code: "MR", title: "Mauritania" },
  { id: 129, code: "MU", title: "Mauritius" },
  { id: 130, code: "MX", title: "Mexico" },
  {
    id: 131,
    code: "FM",
    title: "Micronesia, Federated States of",
  },
  { id: 132, code: "MD", title: "Republic of Moldova" },
  { id: 133, code: "MC", title: "Monaco" },
  { id: 134, code: "MN", title: "Mongolia" },
  { id: 135, code: "ME", title: "Montenegro" },
  { id: 136, code: "MS", title: "Montserrat" },
  { id: 137, code: "MA", title: "Morocco" },
  { id: 138, code: "MZ", title: "Mozambique" },
  { id: 139, code: "MM", title: "Myanmar" },
  { id: 140, code: "NA", title: "Namibia" },
  { id: 141, code: "NR", title: "Nauru" },
  { id: 142, code: "NP", title: "Nepal" },
  { id: 143, code: "NL", title: "Netherlands" },
  { id: 144, code: "NZ", title: "New Zealand" },
  { id: 145, code: "NI", title: "Nicaragua" },
  { id: 146, code: "NE", title: "Niger" },
  { id: 147, code: "NG", title: "Nigeria" },
  { id: 148, code: "NU", title: "Niue" },
  { id: 149, code: "NF", title: "Norfolk Island" },
  {
    id: 150,
    code: "MP",
    title: "Northern Mariana Islands",
  },
  { id: 151, code: "NO", title: "Norway" },
  { id: 152, code: "OM", title: "Oman" },
  { id: 153, code: "PK", title: "Pakistan" },
  { id: 154, code: "PW", title: "Palau" },
  { id: 155, code: "PS", title: "Palestinian Territory" },
  { id: 156, code: "PA", title: "Panama" },
  { id: 157, code: "PG", title: "Papua New Guinea" },
  { id: 158, code: "PY", title: "Paraguay" },
  { id: 159, code: "PE", title: "Peru" },
  { id: 160, code: "PH", title: "Philippines" },
  { id: 161, code: "PN", title: "Pitcairn" },
  { id: 162, code: "PL", title: "Poland" },
  { id: 163, code: "PT", title: "Portugal" },
  { id: 164, code: "PR", title: "Puerto Rico" },
  { id: 165, code: "QA", title: "Qatar" },
  { id: 166, code: "RO", title: "Romania" },
  { id: 167, code: "RU", title: "Russian" },
  { id: 168, code: "RW", title: "Rwanda" },
  { id: 169, code: "KN", title: "Saint Kitts and Nevis" },
  { id: 170, code: "WS", title: "Samoa" },
  { id: 171, code: "SM", title: "San Marino" },
  { id: 172, code: "ST", title: "Sao Tome and Principe" },
  { id: 173, code: "SA", title: "Saudi Arabia" },
  { id: 174, code: "SN", title: "Senegal" },
  { id: 175, code: "RS", title: "Serbia" },
  { id: 176, code: "SC", title: "Seychelles" },
  { id: 177, code: "SL", title: "Sierra Leone" },
  { id: 178, code: "SG", title: "Singapore" },
  { id: 179, code: "SX", title: "Sint Maarten" },
  { id: 180, code: "SK", title: "Slovakia" },
  { id: 181, code: "SI", title: "Slovenia" },
  { id: 182, code: "SB", title: "Solomon Islands" },
  { id: 183, code: "SO", title: "Somalia" },
  { id: 184, code: "ZA", title: "South Africa" },
  { id: 185, code: "SS", title: "South Sudan" },
  { id: 186, code: "ES", title: "Spain" },
  { id: 187, code: "LK", title: "Sri Lanka" },
  { id: 188, code: "SD", title: "Sudan" },
  { id: 189, code: "SR", title: "Surititle" },
  { id: 190, code: "SZ", title: "Swaziland" },
  { id: 191, code: "SE", title: "Sweden" },
  { id: 192, code: "CH", title: "Switzerland" },
  { id: 193, code: "SY", title: "Syria" },
  {
    id: 194,
    code: "TW",
    title: "Taiwan, Province of China",
  },
  { id: 195, code: "TJ", title: "Tajikistan" },
  { id: 196, code: "TZ", title: "Tanzania" },
  { id: 197, code: "TH", title: "Thailand" },
  { id: 198, code: "TG", title: "Togo" },
  { id: 199, code: "TK", title: "Tokelau" },
  { id: 200, code: "TO", title: "Tonga" },
  { id: 201, code: "TT", title: "Trinidad and Tobago" },
  { id: 202, code: "TN", title: "Tunisia" },
  { id: 203, code: "TR", title: "Turkey" },
  { id: 204, code: "TM", title: "Turkmenistan" },
  {
    id: 205,
    code: "TC",
    title: "Turks and Caicos Islands",
  },
  { id: 206, code: "TV", title: "Tuvalu" },
  { id: 207, code: "UG", title: "Uganda" },
  { id: 208, code: "UA", title: "Ukraine" },
  { id: 209, code: "AE", title: "United Arab Emirates" },
  { id: 210, code: "GB", title: "United Kingdom" },
  { id: 211, code: "US", title: "United States" },
  { id: 212, code: "UY", title: "Uruguay" },
  { id: 213, code: "UZ", title: "Uzbekistan" },
  { id: 214, code: "VU", title: "Vanuatu" },
  {
    id: 215,
    code: "VE",
    title: "Venezuela, Bolivarian Republic of",
  },
  { id: 216, code: "VN", title: "Viet Nam" },
  { id: 217, code: "VI", title: "Virgin Islands" },
  { id: 218, code: "YE", title: "Yemen" },
  { id: 219, code: "ZM", title: "Zambia" },
  { id: 220, code: "ZW", title: "Zimbabwe" },
];

export default countries;
